from django.urls import path
from LabourApp import views
urlpatterns=[
    path('',views.home),
    path('home',views.home),
    path('login',views.login),
    path('AgencyReg',views.AgencyReg),
    path('UserReg',views.UserReg),
    path('AdminHome',views.AdminHome),
    path('AgencyHome',views.AgencyHome),
    path('PoliceHome',views.PoliceHome),
    path('UserHome',views.UserHome),
    path('logout',views.logout),
    path('LabourReg',views.LabourReg),
    path('LabourVeri',views.LabourVeri),
    path('LabourAccept',views.LabourAccept),
    # path('LabourReject',views.LabourReject),
    path('PostRequire',views.PostRequire),
    path('SearchLabour',views.SearchLabour),
    path('SearchLabour2',views.SearchLabour2),
    path('UserRequest',views.UserRequest),
    path('AssignLabour',views.AssignLabour),
    path('AssignLabour1',views.AssignLabour1),
    path('SearchSite',views.SearchSite),
    path('SearchStaff',views.SearchStaff),
    path('AdTrackLabour',views.AdTrackLabour),
    path('AgTrackLabour',views.AgTrackLabour),
    path('ViewAssignLab',views.ViewAssignLab),
    path('Payment',views.Payment),
    path('Payment2',views.Payment2),
    path('PayStatus',views.PayStatus),
    path('PayStatus2',views.PayStatus2),
    path('UserAmount',views.UserAmount1),
    path('UserAmount2',views.UserAmount2),
    path('Attendence1',views.Attendence1),
    path('Attendence2',views.Attendence2),
    path('LabourSalary1',views.LabourSalary1),
    path('LabourSalary2',views.LabourSalary2),
    path('LabPaymentHis',views.LabPaymentHis),
    path('PoliceAgency',views.PoliceAgency),
    path('PoliceAgency2',views.PoliceAgency2),
    path('PoliceLabour',views.PoliceLabour),
    path('PoliceLabour2',views.PoliceLabour2),
    path('LabourWork',views.LabourWork),
    path('PostReview',views.PostReview),
    path('ViewReview',views.ViewReview),
    path('AdViewReview',views.AdViewReview),
    path('PostComplaints',views.PostComplaints),
    path('PoliManageComp',views.PoliManageComp),
    path('AdManageComp',views.AdManageComp),
    path('AdClientPayment',views.AdClientPayment),

    path('AssignStatus',views.AssignStatus),
    path('ReqAccept',views.ReqAccept),
    path('ReqReject',views.ReqReject),
    path('AgLabourdetails',views.AgLabourdetails),
    path('Labourdetails',views.Labourdetails),
    path('Agencydetails',views.AgencyDetails),
    path('Userdetails',views.UserDetails),
    path('LabAssignDetails',views.LabAssignDetails),
    path('labour',views.Labour),
    


    # path('RegAccept',views.RegAccept),

    path('hr',views.hr),
]